---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: instalamos apache
      package:
        name: httpd
        state: latest
      tags: install
    - name: levantar servicio httpd y dejarlo persistente al reboot
      service:
        name: httpd
        state: started
        enabled: yes
      tags: config
    - name: creamos index.html
      file:
        path: /var/www/html/index.html
        state: touch
      tags: config
    - name: añadimos contenido a index.html
      copy:
        content: "Hello world. Todo OK hasta aquí"
        dest: /var/www/html/index.html
      tags: config
    - name: Desinstalamos apache
      package:
        name: httpd
        state: absent
      tags: never,uninstall